# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='node.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\nnode.proto\x1a\x0c\x63ommon.proto\"\xf5\x01\n\x04Node\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\x12\x0e\n\x06method\x18\x03 \x01(\t\x12\x0e\n\x06passwd\x18\x04 \x01(\t\x12\x10\n\x08protocol\x18\x05 \x01(\t\x12\x0c\n\x04obfs\x18\x06 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x07 \x01(\t\x12\n\n\x02sn\x18\x08 \x01(\t\x12\x0c\n\x04\x63ity\x18\t \x01(\t\x12\x0f\n\x07\x63ountry\x18\n \x01(\t\x12\x0e\n\x06weight\x18\x0b \x01(\r\x12\x17\n\x0ftransfer_enable\x18\x0c \x01(\t\x12\t\n\x01u\x18\r \x01(\r\x12\t\n\x01\x64\x18\x0e \x01(\r\x12\x16\n\x0e\x66orbidden_port\x18\x0f \x01(\t\"*\n\x10NODE_GEN_REQUEST\x12\x16\n\x0erequire_number\x18\x01 \x02(\r\"N\n\x11NODE_GEN_RESPONSE\x12#\n\x0c\x62\x61seResponse\x18\x01 \x02(\x0b\x32\r.BaseResponse\x12\x14\n\x05nodes\x18\x02 \x03(\x0b\x32\x05.Node\" \n\x12NODE_RESET_REQUEST\x12\n\n\x02id\x18\x01 \x02(\t\"O\n\x13NODE_RESET_RESPONSE\x12#\n\x0c\x62\x61seResponse\x18\x01 \x02(\x0b\x32\r.BaseResponse\x12\x13\n\x04node\x18\x02 \x01(\x0b\x32\x05.Node\"\"\n\x13NODE_REMOVE_REQUEST\x12\x0b\n\x03ids\x18\x01 \x03(\t\";\n\x14NODE_REMOVE_RESPONSE\x12#\n\x0c\x62\x61seResponse\x18\x01 \x02(\x0b\x32\r.BaseResponse\"\x7f\n\x11NODE_LIST_REQUEST\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x10\n\x08protocol\x18\x02 \x01(\t\x12\x0c\n\x04obfs\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\n\n\x02id\x18\x05 \x01(\t\x12\x0c\n\x04\x63ity\x18\x06 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x07 \x01(\t\"O\n\x12NODE_LIST_RESPONSE\x12#\n\x0c\x62\x61seResponse\x18\x01 \x02(\x0b\x32\r.BaseResponse\x12\x14\n\x05nodes\x18\x02 \x03(\x0b\x32\x05.Node')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='Node.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='Node.port', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='method', full_name='Node.method', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='passwd', full_name='Node.passwd', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='protocol', full_name='Node.protocol', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='obfs', full_name='Node.obfs', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='Node.address', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sn', full_name='Node.sn', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='city', full_name='Node.city', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='Node.country', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight', full_name='Node.weight', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transfer_enable', full_name='Node.transfer_enable', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u', full_name='Node.u', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='d', full_name='Node.d', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='forbidden_port', full_name='Node.forbidden_port', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=274,
)


_NODE_GEN_REQUEST = _descriptor.Descriptor(
  name='NODE_GEN_REQUEST',
  full_name='NODE_GEN_REQUEST',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='require_number', full_name='NODE_GEN_REQUEST.require_number', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=318,
)


_NODE_GEN_RESPONSE = _descriptor.Descriptor(
  name='NODE_GEN_RESPONSE',
  full_name='NODE_GEN_RESPONSE',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='baseResponse', full_name='NODE_GEN_RESPONSE.baseResponse', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='NODE_GEN_RESPONSE.nodes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=398,
)


_NODE_RESET_REQUEST = _descriptor.Descriptor(
  name='NODE_RESET_REQUEST',
  full_name='NODE_RESET_REQUEST',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='NODE_RESET_REQUEST.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=432,
)


_NODE_RESET_RESPONSE = _descriptor.Descriptor(
  name='NODE_RESET_RESPONSE',
  full_name='NODE_RESET_RESPONSE',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='baseResponse', full_name='NODE_RESET_RESPONSE.baseResponse', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node', full_name='NODE_RESET_RESPONSE.node', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=434,
  serialized_end=513,
)


_NODE_REMOVE_REQUEST = _descriptor.Descriptor(
  name='NODE_REMOVE_REQUEST',
  full_name='NODE_REMOVE_REQUEST',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='NODE_REMOVE_REQUEST.ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=549,
)


_NODE_REMOVE_RESPONSE = _descriptor.Descriptor(
  name='NODE_REMOVE_RESPONSE',
  full_name='NODE_REMOVE_RESPONSE',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='baseResponse', full_name='NODE_REMOVE_RESPONSE.baseResponse', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=551,
  serialized_end=610,
)


_NODE_LIST_REQUEST = _descriptor.Descriptor(
  name='NODE_LIST_REQUEST',
  full_name='NODE_LIST_REQUEST',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='NODE_LIST_REQUEST.method', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='protocol', full_name='NODE_LIST_REQUEST.protocol', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='obfs', full_name='NODE_LIST_REQUEST.obfs', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='NODE_LIST_REQUEST.address', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='NODE_LIST_REQUEST.id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='city', full_name='NODE_LIST_REQUEST.city', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='NODE_LIST_REQUEST.country', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=612,
  serialized_end=739,
)


_NODE_LIST_RESPONSE = _descriptor.Descriptor(
  name='NODE_LIST_RESPONSE',
  full_name='NODE_LIST_RESPONSE',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='baseResponse', full_name='NODE_LIST_RESPONSE.baseResponse', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='NODE_LIST_RESPONSE.nodes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=741,
  serialized_end=820,
)

_NODE_GEN_RESPONSE.fields_by_name['baseResponse'].message_type = common__pb2._BASERESPONSE
_NODE_GEN_RESPONSE.fields_by_name['nodes'].message_type = _NODE
_NODE_RESET_RESPONSE.fields_by_name['baseResponse'].message_type = common__pb2._BASERESPONSE
_NODE_RESET_RESPONSE.fields_by_name['node'].message_type = _NODE
_NODE_REMOVE_RESPONSE.fields_by_name['baseResponse'].message_type = common__pb2._BASERESPONSE
_NODE_LIST_RESPONSE.fields_by_name['baseResponse'].message_type = common__pb2._BASERESPONSE
_NODE_LIST_RESPONSE.fields_by_name['nodes'].message_type = _NODE
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['NODE_GEN_REQUEST'] = _NODE_GEN_REQUEST
DESCRIPTOR.message_types_by_name['NODE_GEN_RESPONSE'] = _NODE_GEN_RESPONSE
DESCRIPTOR.message_types_by_name['NODE_RESET_REQUEST'] = _NODE_RESET_REQUEST
DESCRIPTOR.message_types_by_name['NODE_RESET_RESPONSE'] = _NODE_RESET_RESPONSE
DESCRIPTOR.message_types_by_name['NODE_REMOVE_REQUEST'] = _NODE_REMOVE_REQUEST
DESCRIPTOR.message_types_by_name['NODE_REMOVE_RESPONSE'] = _NODE_REMOVE_RESPONSE
DESCRIPTOR.message_types_by_name['NODE_LIST_REQUEST'] = _NODE_LIST_REQUEST
DESCRIPTOR.message_types_by_name['NODE_LIST_RESPONSE'] = _NODE_LIST_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), dict(
  DESCRIPTOR = _NODE,
  __module__ = 'node_pb2'
  # @@protoc_insertion_point(class_scope:Node)
  ))
_sym_db.RegisterMessage(Node)

NODE_GEN_REQUEST = _reflection.GeneratedProtocolMessageType('NODE_GEN_REQUEST', (_message.Message,), dict(
  DESCRIPTOR = _NODE_GEN_REQUEST,
  __module__ = 'node_pb2'
  # @@protoc_insertion_point(class_scope:NODE_GEN_REQUEST)
  ))
_sym_db.RegisterMessage(NODE_GEN_REQUEST)

NODE_GEN_RESPONSE = _reflection.GeneratedProtocolMessageType('NODE_GEN_RESPONSE', (_message.Message,), dict(
  DESCRIPTOR = _NODE_GEN_RESPONSE,
  __module__ = 'node_pb2'
  # @@protoc_insertion_point(class_scope:NODE_GEN_RESPONSE)
  ))
_sym_db.RegisterMessage(NODE_GEN_RESPONSE)

NODE_RESET_REQUEST = _reflection.GeneratedProtocolMessageType('NODE_RESET_REQUEST', (_message.Message,), dict(
  DESCRIPTOR = _NODE_RESET_REQUEST,
  __module__ = 'node_pb2'
  # @@protoc_insertion_point(class_scope:NODE_RESET_REQUEST)
  ))
_sym_db.RegisterMessage(NODE_RESET_REQUEST)

NODE_RESET_RESPONSE = _reflection.GeneratedProtocolMessageType('NODE_RESET_RESPONSE', (_message.Message,), dict(
  DESCRIPTOR = _NODE_RESET_RESPONSE,
  __module__ = 'node_pb2'
  # @@protoc_insertion_point(class_scope:NODE_RESET_RESPONSE)
  ))
_sym_db.RegisterMessage(NODE_RESET_RESPONSE)

NODE_REMOVE_REQUEST = _reflection.GeneratedProtocolMessageType('NODE_REMOVE_REQUEST', (_message.Message,), dict(
  DESCRIPTOR = _NODE_REMOVE_REQUEST,
  __module__ = 'node_pb2'
  # @@protoc_insertion_point(class_scope:NODE_REMOVE_REQUEST)
  ))
_sym_db.RegisterMessage(NODE_REMOVE_REQUEST)

NODE_REMOVE_RESPONSE = _reflection.GeneratedProtocolMessageType('NODE_REMOVE_RESPONSE', (_message.Message,), dict(
  DESCRIPTOR = _NODE_REMOVE_RESPONSE,
  __module__ = 'node_pb2'
  # @@protoc_insertion_point(class_scope:NODE_REMOVE_RESPONSE)
  ))
_sym_db.RegisterMessage(NODE_REMOVE_RESPONSE)

NODE_LIST_REQUEST = _reflection.GeneratedProtocolMessageType('NODE_LIST_REQUEST', (_message.Message,), dict(
  DESCRIPTOR = _NODE_LIST_REQUEST,
  __module__ = 'node_pb2'
  # @@protoc_insertion_point(class_scope:NODE_LIST_REQUEST)
  ))
_sym_db.RegisterMessage(NODE_LIST_REQUEST)

NODE_LIST_RESPONSE = _reflection.GeneratedProtocolMessageType('NODE_LIST_RESPONSE', (_message.Message,), dict(
  DESCRIPTOR = _NODE_LIST_RESPONSE,
  __module__ = 'node_pb2'
  # @@protoc_insertion_point(class_scope:NODE_LIST_RESPONSE)
  ))
_sym_db.RegisterMessage(NODE_LIST_RESPONSE)


# @@protoc_insertion_point(module_scope)
