// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class BaseResponse;
@class DeviceProto;
@class MessageInfo;
@class UserProto;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UserRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface UserRoot : GPBRootObject
@end

#pragma mark - UserRegisterRequest

typedef GPB_ENUM(UserRegisterRequest_FieldNumber) {
  UserRegisterRequest_FieldNumber_Username = 1,
};

@interface UserRegisterRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;
/** Test to see if @c username has been set. */
@property(nonatomic, readwrite) BOOL hasUsername;

@end

#pragma mark - MessageSendRequest

typedef GPB_ENUM(MessageSendRequest_FieldNumber) {
  MessageSendRequest_FieldNumber_TargetsArray = 1,
  MessageSendRequest_FieldNumber_Message = 2,
};

@interface MessageSendRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *targetsArray;
/** The number of items in @c targetsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger targetsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) MessageInfo *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@end

#pragma mark - MessageNotifyRequest

typedef GPB_ENUM(MessageNotifyRequest_FieldNumber) {
  MessageNotifyRequest_FieldNumber_Message = 1,
};

@interface MessageNotifyRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MessageInfo *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@end

#pragma mark - DeviceProto

typedef GPB_ENUM(DeviceProto_FieldNumber) {
  DeviceProto_FieldNumber_DeviceId = 1,
  DeviceProto_FieldNumber_UserId = 2,
  DeviceProto_FieldNumber_Status = 3,
  DeviceProto_FieldNumber_AppVersion = 4,
  DeviceProto_FieldNumber_DeviceName = 5,
  DeviceProto_FieldNumber_DeviceOs = 6,
  DeviceProto_FieldNumber_DeviceType = 7,
  DeviceProto_FieldNumber_Ip = 8,
  DeviceProto_FieldNumber_Location = 9,
  DeviceProto_FieldNumber_Isp = 10,
  DeviceProto_FieldNumber_NetStatus = 11,
  DeviceProto_FieldNumber_Online = 12,
  DeviceProto_FieldNumber_LastCheck = 13,
  DeviceProto_FieldNumber_LastLogin = 14,
  DeviceProto_FieldNumber_Created = 15,
};

@interface DeviceProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;
/** Test to see if @c deviceId has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;
/** Test to see if @c userId has been set. */
@property(nonatomic, readwrite) BOOL hasUserId;

@property(nonatomic, readwrite) uint32_t status;

@property(nonatomic, readwrite) BOOL hasStatus;
@property(nonatomic, readwrite, copy, null_resettable) NSString *appVersion;
/** Test to see if @c appVersion has been set. */
@property(nonatomic, readwrite) BOOL hasAppVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceName;
/** Test to see if @c deviceName has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceName;

@property(nonatomic, readwrite) uint32_t deviceOs;

@property(nonatomic, readwrite) BOOL hasDeviceOs;
@property(nonatomic, readwrite) uint32_t deviceType;

@property(nonatomic, readwrite) BOOL hasDeviceType;
@property(nonatomic, readwrite, copy, null_resettable) NSString *ip;
/** Test to see if @c ip has been set. */
@property(nonatomic, readwrite) BOOL hasIp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *location;
/** Test to see if @c location has been set. */
@property(nonatomic, readwrite) BOOL hasLocation;

@property(nonatomic, readwrite, copy, null_resettable) NSString *isp;
/** Test to see if @c isp has been set. */
@property(nonatomic, readwrite) BOOL hasIsp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *netStatus;
/** Test to see if @c netStatus has been set. */
@property(nonatomic, readwrite) BOOL hasNetStatus;

@property(nonatomic, readwrite) BOOL online;

@property(nonatomic, readwrite) BOOL hasOnline;
@property(nonatomic, readwrite) uint32_t lastCheck;

@property(nonatomic, readwrite) BOOL hasLastCheck;
@property(nonatomic, readwrite) uint32_t lastLogin;

@property(nonatomic, readwrite) BOOL hasLastLogin;
@property(nonatomic, readwrite) uint32_t created;

@property(nonatomic, readwrite) BOOL hasCreated;
@end

#pragma mark - UserProto

typedef GPB_ENUM(UserProto_FieldNumber) {
  UserProto_FieldNumber_UserId = 1,
  UserProto_FieldNumber_Phone = 2,
  UserProto_FieldNumber_Nickname = 3,
  UserProto_FieldNumber_Status = 4,
  UserProto_FieldNumber_Role = 5,
  UserProto_FieldNumber_Created = 6,
  UserProto_FieldNumber_RemainTime = 7,
};

@interface UserProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;
/** Test to see if @c userId has been set. */
@property(nonatomic, readwrite) BOOL hasUserId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *phone;
/** Test to see if @c phone has been set. */
@property(nonatomic, readwrite) BOOL hasPhone;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;
/** Test to see if @c nickname has been set. */
@property(nonatomic, readwrite) BOOL hasNickname;

@property(nonatomic, readwrite) uint32_t status;

@property(nonatomic, readwrite) BOOL hasStatus;
@property(nonatomic, readwrite) uint32_t role;

@property(nonatomic, readwrite) BOOL hasRole;
@property(nonatomic, readwrite) uint32_t created;

@property(nonatomic, readwrite) BOOL hasCreated;
@property(nonatomic, readwrite) uint32_t remainTime;

@property(nonatomic, readwrite) BOOL hasRemainTime;
@end

#pragma mark - INIT_RESPONSE

typedef GPB_ENUM(INIT_RESPONSE_FieldNumber) {
  INIT_RESPONSE_FieldNumber_BaseResponse = 1,
  INIT_RESPONSE_FieldNumber_DeviceResponse = 2,
  INIT_RESPONSE_FieldNumber_UserResponse = 3,
};

@interface INIT_RESPONSE : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite, strong, null_resettable) DeviceProto *deviceResponse;
/** Test to see if @c deviceResponse has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceResponse;

@property(nonatomic, readwrite, strong, null_resettable) UserProto *userResponse;
/** Test to see if @c userResponse has been set. */
@property(nonatomic, readwrite) BOOL hasUserResponse;

@end

#pragma mark - NEED_REGISTER_DEVICE_RESPONSE

typedef GPB_ENUM(NEED_REGISTER_DEVICE_RESPONSE_FieldNumber) {
  NEED_REGISTER_DEVICE_RESPONSE_FieldNumber_BaseResponse = 1,
};

@interface NEED_REGISTER_DEVICE_RESPONSE : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@end

#pragma mark - DEVICE_REGISTER_REQUEST

typedef GPB_ENUM(DEVICE_REGISTER_REQUEST_FieldNumber) {
  DEVICE_REGISTER_REQUEST_FieldNumber_DeviceId = 1,
  DEVICE_REGISTER_REQUEST_FieldNumber_AppVersion = 2,
  DEVICE_REGISTER_REQUEST_FieldNumber_DeviceName = 3,
  DEVICE_REGISTER_REQUEST_FieldNumber_DeviceOs = 4,
  DEVICE_REGISTER_REQUEST_FieldNumber_DeviceType = 5,
};

@interface DEVICE_REGISTER_REQUEST : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;
/** Test to see if @c deviceId has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appVersion;
/** Test to see if @c appVersion has been set. */
@property(nonatomic, readwrite) BOOL hasAppVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceName;
/** Test to see if @c deviceName has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceName;

@property(nonatomic, readwrite) uint32_t deviceOs;

@property(nonatomic, readwrite) BOOL hasDeviceOs;
@property(nonatomic, readwrite) uint32_t deviceType;

@property(nonatomic, readwrite) BOOL hasDeviceType;
@end

#pragma mark - DEVICE_REGISTER_RESPONSE

typedef GPB_ENUM(DEVICE_REGISTER_RESPONSE_FieldNumber) {
  DEVICE_REGISTER_RESPONSE_FieldNumber_BaseResponse = 1,
  DEVICE_REGISTER_RESPONSE_FieldNumber_DeviceResponse = 2,
};

@interface DEVICE_REGISTER_RESPONSE : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite, strong, null_resettable) DeviceProto *deviceResponse;
/** Test to see if @c deviceResponse has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceResponse;

@end

#pragma mark - DEVICE_UPDATE_REQUEST

typedef GPB_ENUM(DEVICE_UPDATE_REQUEST_FieldNumber) {
  DEVICE_UPDATE_REQUEST_FieldNumber_DeviceId = 1,
  DEVICE_UPDATE_REQUEST_FieldNumber_UserId = 2,
  DEVICE_UPDATE_REQUEST_FieldNumber_Status = 3,
  DEVICE_UPDATE_REQUEST_FieldNumber_AppVersion = 4,
  DEVICE_UPDATE_REQUEST_FieldNumber_DeviceName = 5,
  DEVICE_UPDATE_REQUEST_FieldNumber_DeviceOs = 6,
  DEVICE_UPDATE_REQUEST_FieldNumber_DeviceType = 7,
  DEVICE_UPDATE_REQUEST_FieldNumber_NetStatus = 8,
};

@interface DEVICE_UPDATE_REQUEST : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;
/** Test to see if @c deviceId has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;
/** Test to see if @c userId has been set. */
@property(nonatomic, readwrite) BOOL hasUserId;

@property(nonatomic, readwrite) uint32_t status;

@property(nonatomic, readwrite) BOOL hasStatus;
@property(nonatomic, readwrite, copy, null_resettable) NSString *appVersion;
/** Test to see if @c appVersion has been set. */
@property(nonatomic, readwrite) BOOL hasAppVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceName;
/** Test to see if @c deviceName has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceName;

@property(nonatomic, readwrite) uint32_t deviceOs;

@property(nonatomic, readwrite) BOOL hasDeviceOs;
@property(nonatomic, readwrite) uint32_t deviceType;

@property(nonatomic, readwrite) BOOL hasDeviceType;
@property(nonatomic, readwrite, copy, null_resettable) NSString *netStatus;
/** Test to see if @c netStatus has been set. */
@property(nonatomic, readwrite) BOOL hasNetStatus;

@end

#pragma mark - DEVICE_UPDATE_RESPONSE

typedef GPB_ENUM(DEVICE_UPDATE_RESPONSE_FieldNumber) {
  DEVICE_UPDATE_RESPONSE_FieldNumber_BaseResponse = 1,
  DEVICE_UPDATE_RESPONSE_FieldNumber_DeviceResponse = 2,
};

@interface DEVICE_UPDATE_RESPONSE : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@property(nonatomic, readwrite, strong, null_resettable) DeviceProto *deviceResponse;
/** Test to see if @c deviceResponse has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceResponse;

@end

#pragma mark - DEVICE_DELETE_REQUEST

typedef GPB_ENUM(DEVICE_DELETE_REQUEST_FieldNumber) {
  DEVICE_DELETE_REQUEST_FieldNumber_DeviceId = 1,
};

@interface DEVICE_DELETE_REQUEST : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;
/** Test to see if @c deviceId has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceId;

@end

#pragma mark - DEVICE_DELETE_RESPONSE

typedef GPB_ENUM(DEVICE_DELETE_RESPONSE_FieldNumber) {
  DEVICE_DELETE_RESPONSE_FieldNumber_BaseResponse = 1,
};

@interface DEVICE_DELETE_RESPONSE : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseResponse *baseResponse;
/** Test to see if @c baseResponse has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResponse;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
